# Package Overview
package_name: sentiment_model

# Data Files/content/Reviews.csv
training_data_file: Reviews.csv
test_data_file: test.csv


# Ajay Singh (Aug 18)
# Data Files
train_path: train
validation_path: validation
test_path: test

# Variables
target: Sentiment

pipeline_name: sentiment_model
pipeline_save_file: sentiment__model_output_v

#Ajay (Aug 18)
model_name: sentiment_model
model_save_file: sentiment__model_output_v

    
embedding_dim: 64
max_num_words: 50000
max_sequence_length: 100
tokenizer_filename : strtokenizer_custom.txt

# Feature engineering parameters
flip: horizontal

batch_size: 32
random_state: 0
epochs: 3
optimizer: adam
loss: binary_crossentropy
accuracy_metric: accuracy
verbose: 1  #1: Display progress bar for each epoch. 2:Display one line per epoch.
earlystop: 0
monitor: val_loss #Choosing 'val_loss' to prevent overfitting and ensure good generalization. 'val_accuracy' can be tried for good accuracy
save_best_only: True
input_dim: 5000
output_dim: 64
dropout: 0.2
rdropout: 0.2
units: 40

# set train/test split
test_size: 0.20
test_size2: 0.25




features:      # final features to be use
  - ProductId
  - UserId
  - ProfileName 
  - Score 
  - Time
  - Summary  
  - Text
  
unused_fields:  # Features to drop before pipeline
  - Id
  - HelpfulnessNumerator
  - HelpfulnessDenominator
  