# Package Overview
package_name: sentiment_model

# Data Files/content/Reviews.csv
training_data_file: Reviews.csv
test_data_file: test.csv

# Variables
# The variable we are attempting to predict (Survival)
target: Sentiment

pipeline_name: sentiment_model
pipeline_save_file: sentiment__model_output_v

features:      # final features to be use
  - ProductId
  - UserId
  - ProfileName 
  - Score 
  - Time
  - Summary  
  - Text
  
unused_fields:  # Features to drop before pipeline
  - Id
  - HelpfulnessNumerator
  - HelpfulnessDenominator
  