# Package Overview
package_name: sentiment_model

# Data Files
# Data Files
training_data_file: Reviews.csv
test_data_file: test.csv


model_name: sentiment_model
model_save_file: sentiment__model_output_v


# Set the random seed
random_state: 42

# Alogrithm parameters
batch_size: 64
epochs: 3
verbose: 1
earlystop: 0
monitor: val_loss
save_best_only: True

embedding_dim: 100
max_num_words: 50000
max_sequence_length: 100
tokenizer_filename : tokenizer_custom

#Model Confirm parameters
input_dim: 5000
output_dim: 64
optimizer: adam 
loss: binary_crossentropy
accuracy_metric: accuracy
dropout: 0.2
rdropout: 0.2
units: 40

unused_fields:  # Features to drop before pipeline
  - Id
  - HelpfulnessNumerator
  - HelpfulnessDenominator
  