# Package Overview
package_name: sentiment_model

# Data Files/content/Reviews.csv
training_data_file: Reviews.csv
test_data_file: test.csv

# Variables
# The variable we are attempting to predict (Survival)
target: Sentiment

pipeline_name: sentiment_model
pipeline_save_file: sentiment__model_output_v

features:      # final features to be use
  - ProductId
  - UserId
  - ProfileName 
  - Score 
  - Time
  - Summary  
  - Text
  
unused_fields:  # Features to drop before pipeline
  - Id
  - HelpfulnessNumerator
  - HelpfulnessDenominator
  
# Features inside processing pipeline
Time_var: Time
Text_var: Text


# set train/test split
test_size: 0.20

# to set the random seed
random_state: 42
# alogrithm parameters
n_estimators: 150
max_depth: 5

# LSTM params
units:40
dropout:0.2
recurrent_dropout:0.2








